#!/bin/sh
# As I am not very happy with the PyPI versioning, I will suggest some
# should-work-for-all workaround solution.
#
# What am I missing?
#  * Simpel solution
#  * Automatic versioning (fire-and-forget)
#  * Still supporting manual versions
#  * Unambiguous versions, even across branches or forks
#  * Still PEP440 conform - (there is only one branch at PyPI..)

# If someone has a simpler, yet equally powerful, idea, please send it to
# me (mic at inofix.ch).

version_file=version.txt
#setup_file=setup.py

if ! git describe >/dev/null 2>&1 ; then
    echo "This project has no version info yet! Use 'git tag -a <version>'"
    exit 1
fi

if ! git diff --quiet HEAD ; then
    # something has changed in the repository
    if git diff --quiet ; then
        # this means all changes were added

        new_version=`git describe`
        old_version=`grep "^Real Version: .*$" $version_file | awk '{print $3}'`

        if [ "$new_version" != "$old_version" ] ; then

            i=0
            for v in `echo $new_version | tr "-" " "` ; do
                eval "v_$i=$v"
                i=$(($i+1))
            done

            official_version="$v_0"

            if [ -n "$v_1" ] ; then
                official_version="$v_0.dev$v_1"
            fi

            echo "The main script has changed, count up the version to $new_version ($official_version resp.)"

            sed -i 's;^Real Version: .*$;Real Version: '${new_version}';' $version_file
            sed -i 's;^Official Version: .*$;Official Version: '${official_version}';' $version_file
            git add $version_file
#            sed -i "s;    version='.*',;    version='${official_version}',;" $setup_file
#            git add $setup_file
        fi
    fi
fi

